version: "3.6"

services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017

  # emeritus:
  #   #image: ivanzy/emeritus:demo
  #   build: .
  #   links:
  #     - "mongo:mongo"
  #   ports:
  #     - "2022:2022"
  #   depends_on:
  #     - mongo
