
//Duty: 35 - batV: 2.55
//cea877bb-1d63-4cf3-8c88-eccec0729234
###
POST http://192.168.1.3:2022/harvester/simulation
Content-Type: application/json

{
  "devId": "restre",
	"harvId": "SolarHeavyLoad",
	"lowpwrI": 400,
	"activeI": 715,
	"duty":25,
	"Vload": 5,
  "devAvgI": null,
	"batSOC": null,
	"batV": 2.55,
	"phIrr": 700,
	"thThot": null,
	"thTcold": null,
	"thGrad": null,
	"vibAcc": null,
	"vibFreq": null
}


###

GET http://192.168.1.3:2022/harvester/simulation/e0612c0597872cb6b0b86f3995d8536b9935d976
###
POST http://localhost:2022/harvester/simulation
Content-Type: application/json

{
    "devId": "ClusterHead",
    "harvId": "SolarHeavyLoad",
    "lowpwrI": 400,
    "activeI": 715,
    "duty": 20,
    "Vload": 5,
    "devAvgI": null,
    "batSOC": null,
    "batV": "2.55",
    "phIrr": 700,
    "thThot": null,
    "thTcold": null,
    "thGrad": null,
    "vibAcc": null,
    "vibFreq": null
}

//de4bb2e592f5d52a37aaefd7ae885ec807996f2a

################################
POST http://localhost:2022/harvester/simulation/
Content-Type: application/json

{
    "harvId": "SolarLightLoad",
    "lowpwrI": 3,
    "activeI": 10,
    "duty": 20,
    "Vload": 3.3,
    "thThot": null,
    "devAvgI": null,
    "batSOC": null,
    "phIrr": 700,
    "thTcold": null,
    "thGrad": null,
    "vibAcc": null,
    "vibFreq": null,
    "batV": 3.15

}

//acb1a59cef38ddc3c3c0a68f23b14534e8012b90

//bf72aa166c8f591e6b3c7c9602d8960e5516e149



################################################################


POST http://localhost:2022/harvester/simulation/hash
Content-Type: application/json

{

"devId":"GasSensor",
"harvId":"SolarLightLoad",
"lowpwrI":3,
"activeI":10,
"duty":20,
"Vload":3.3,
"devAvgI":null,
"batSOC":null,
"batV":"3.15",
"phIrr":700,
"thThot":null,
"thTcold":null,
"thGrad":null,
"vibAcc":null,
"vibFreq":null
}