
//Duty: 35 - batV: 2.55
//cea877bb-1d63-4cf3-8c88-eccec0729234
###
POST http://localhost:2022/harvester/simulation
Content-Type: application/json

{
  "devId": "asdasdasd",
	"harvId": "SolarHeavyLoad",
	"lowpwrI": 400,
	"activeI": 715,
	"duty":90,
	"Vload": 5,
  "devAvgI": null,
	"batSOC": null,
	"batV": 3,
	"phIrr": 700,
	"thThot": null,
	"thTcold": null,
	"thGrad": null,
	"vibAcc": null,
	"vibFreq": null
}


###

GET http://localhost:2022/harvester/simulation/f250064da3ea165684e88648ae4d2b5d28e60ccb